In [ ]:
# In particular, a research group in Computer Science at UBC, led by Frank Wood, is collecting data about how people play
# video games. They have set up a MineCraft server, and players' actions are recorded as they navigate through the world. 
# But running this project is not simple: they need to target their recruitment efforts, and make sure they have enough resources
# (e.g., software licenses, server hardware) to handle the number of players they attract.

In [ ]:
# submit as .html and as .ipynb
# max 500 words (non-inclusive of code)
# should not require other files (no reading in data, just name variables & etc)

# chosen question (Question 2):
# We would like to know which "kinds" of players are most likely to contribute
# a large amount of data so that we can target those players in our recruiting efforts.

# should only need players.csv to answer this question

In [1]:
# the problem (dissected):
# "contribute a large amount of data" = high played hours
# predicting high played hours based on other qualities = k-nn regression
# player data -> -> k-nn regression

In [2]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

**1. Data Description**
The dataset I am using, `players.csv`, has 196 observations with 7 variables. The variables are described in the table below:

In [18]:
variable_desc_table <- data.frame(
    name = c("experience", "subscribe", "hashedEmail", "played_hours", "name", "gender", "Age"),
    type = c("character", "logical", "character", "double", "character", "character", "double"),
    mean_stat_if_dbl = c("NA", "NA", "NA", "5.85", "NA", "NA", "21.14"),
    description = c("The experience level of the player in playing Minecraft (Beginner, Amateur, Regular, Pro, 
                    Veteran)", "If the player is subscribed to the gaming newsletter", "Anonymous representation
                    of player's email address", "Hours played on Minecraft server", "Player's first name", "Player's 
                    gender (Male, Female, Non-binary, Two-Spirited, Agender, Prefer not to say, Other)", "Player's age")
    )
variable_desc_table

  name         type      mean_stat_if_dbl
1 experience   character NA
2 subscribe    logical   NA
3 hashedEmail  character NA
4 played_hours double    5.85
5 name         character NA
6 gender       character NA
7 Age          double    21.14
  description
1 The experience level of the player in playing Minecraft (Beginner, Amateur, Regular, Pro, \n                    Veteran)
2 If the player is subscribed to the gaming newsletter
3 Anonymous representation\n                    of player's email address
4 Hours played on Minecraft server
5 Player's first name
6 Player's \n                    gender (Male, Female, Non-binary, Two-Spirited, Agender, Prefer not to say, Other)
7 Player's age

The only issue that comes to mind when dealing with the data is the use of the hashed emails as the only real unique distinctive value between each observation, since they are such long and random character strings that aren't easy for humans to read. While I couldn't see any duplicate player names, it is still possible I missed one given the number of observations, so it is not a good variable to use for this. However, I do not forsee a need to filter for an individual observation often (if at all), so I am not concerned. Additionally, I noticed there are some seemingly odd name and gender pairings, given societal naming conventions, which could be indicative of the data being transferred to the `.csv` file incorrectly. That is the only reason I note it, but there are likely other explanations, so I assume it to be a non-issue in the meantime. Lastly, some observations have `NA` in the `Age` variable, but that is easy to resolve with filtration. 

I cannot see how the data was collected, but my assumption is that player identity it was through an email survey form based on the hashed emails, and then some other program likely used that identity data to track hours of play per player. The most important variable here is the played hours, as it is what will be used to represent the amount of data a player contributes to the study (more hours = more data). The other variables will be used to predict the hours played via a regression model.

In [19]:
players <- read_csv("data/players.csv")

summary_stats <- summarize(players, 
                           avg_played_hours = mean(played_hours, na.rm = TRUE),
                           avg_age = mean(Age, na.rm = TRUE))
summary_stats

  avg_played_hours avg_age
1 5.845918         21.13918

**2. Questions**

Broad question: *What "kinds" of players are most likely to contribute the most amount of data to the study by contributing higher hours of play?*

My specific questions:
- Can player age help predict hours of play on the Minecraft server?
- Does gender help predict hours of play on the Minecraft server?
- Can player experience help predict hours of play on the Minecraft server?
- Which of the prior 3 variables is the strongest predictor for hours of play?
- What is the mode gender and experience level as well as the mode age range (by ranges <18, 18-20, 21-24, >24) of the top 10 players by hours contributed?

The data will help me explore the broader question and its more specific questions by providing values for the variables of age, gender, experience, and hours played in observations that relate them together. I will need to use filtration to wrangle the data to answer some of my questions to filter out `NA`s, select for the 10 players with the highest play time, and to filter for other qualities such as certain ages.

(3) Exploratory Data Analysis and Visualization
In this assignment, you will:

Demonstrate that the dataset can be loaded into R.
Do the minimum necessary wrangling to turn your data into a tidy format. Do not do any additional wrangling here; that will happen later during the group project phase.
Compute the mean value for each quantitative variable in the players.csv data set. Report the mean values in a table format.
Make a few exploratory visualizations of the data to help you understand it.
Use our visualization best practices to make high-quality plots (make sure to include labels, titles, units of measurement, etc)
Explain any insights you gain from these plots that are relevant to address your question
Note: do not perform any predictive analysis here. We are asking for an exploration of the relevant variables to demonstrate that you understand them well before performing any additional modelling, and to identify potential problems you anticipate encountering.

**3. Exploratory Data Analysis and Visualization**

See cell 19 for where I read in the dataset.

In [20]:
head(players)

  experience subscribe
1 Pro         TRUE
2 Veteran     TRUE
3 Veteran    FALSE
4 Amateur     TRUE
5 Regular     TRUE
6 Amateur     TRUE
  hashedEmail                                                      played_hours
1 f6daba428a5e19a3d47574858c13550499be23603422e6a0ee9728f8b53e192d 30.3
2 f3c813577c458ba0dfef80996f8f32c93b6e8af1fa939732842f2312358a88e9  3.8
3 b674dd7ee0d24096d1c019615ce4d12b20fcbff12d79d3c5a9d2118eb7ccbb28  0.0
4 23fe711e0e3b77f1da7aa221ab1192afe21648d47d2b4fa7a5a659ff443a0eb5  0.7
5 7dc01f10bf20671ecfccdac23812b1b415acd42c2147cb0af4d48fcce2420f3e  0.1
6 f58aad5996a435f16b0284a3b267f973f9af99e7a89bee0430055a44fa92f977  0.0
  name      gender Age
1 Morgan    Male    9
2 Christian Male   17
3 Blake     Male   17
4 Flora     Female 21
5 Kylie     Male   21
6 Adrian    Female 17

The data set already meets the requirements for tidy data based on the research question:

1. Each observation is a single row.
2. Each column is a single variable (and all variables for the statistical questions are in columns, not as values).
3. Each cell contains a single value.

The `sessions.csv` file, which is irrelevant to these questions, does have issues with the start and end time variables, as they contain year, month, day, AND time in a single cell. The start and end times would need to be widened with `pivot_widen()` into separate variables for each component, but again, that is not the data I am using.

I will wrangle the data now to remove any instances of `NA` in `Age` (the only column containing any `NA`s) and the `name` and `subscribe` variables to demonstrate some tidying:

In [22]:
tidy_players <- players |>
    filter(!is.na(Age)) |>
    select(experience, hashedEmail, played_hours, gender, Age)

tidy_players

    experience hashedEmail
1   Pro        f6daba428a5e19a3d47574858c13550499be23603422e6a0ee9728f8b53e192d
2   Veteran    f3c813577c458ba0dfef80996f8f32c93b6e8af1fa939732842f2312358a88e9
3   Veteran    b674dd7ee0d24096d1c019615ce4d12b20fcbff12d79d3c5a9d2118eb7ccbb28
4   Amateur    23fe711e0e3b77f1da7aa221ab1192afe21648d47d2b4fa7a5a659ff443a0eb5
5   Regular    7dc01f10bf20671ecfccdac23812b1b415acd42c2147cb0af4d48fcce2420f3e
6   Amateur    f58aad5996a435f16b0284a3b267f973f9af99e7a89bee0430055a44fa92f977
7   Regular    8e594b8953193b26f498db95a508b03c6fe1c24bb5251d392c18a0da9a722807
8   Amateur    1d2371d8a35c8831034b25bda8764539ab7db0f63938696917c447128a2540dd
9   Amateur    8b71f4d66a38389b7528bb38ba6eb71157733df7d1740371852a797ae97d82d1
10  Veteran    bbe2d83de678f519c4b3daa7265e683b4fe2d814077f9094afd11d8f217039ec
11  Veteran    7a4686586d290c67179275c7c3dfb4ea02f4d317d9ee0e2cee98baa27877a875
12  Pro        4caa42e1b20511552434978171dcf7283fb6eb857eb871327e39bfc328002309
13  Beginner   4bed6f49b672974f706aa7f020b4f29020326bf594520593557cd381a51559b8
14  Amateur    3caa832978e0596779f4ee7c686c4592fb6de893925025d25bf26be9a8cd03f5
15  Veteran    6f9acf8ea9956fe817895c78d10e1e25c11aba335a451e5b0322b073ee5008c4
16  Amateur    2313a06afe47eacc28ff55adf6f072e7d12b0d12d7cbae29656f9029ec72bb53
17  Beginner   9db37a1d381697f6c83e3b97b276e38bb9d9c811ba4596edb75d4dbfea6415b0
18  Amateur    a175d4741dc84e6baf77901f6e8e0a06f54809a34e6b5211159bced346f7fb3e
19  Amateur    ab1f44f93c3b828f55458971db393052d9711df3e0e7ff69540bfebfcec555ff
20  Regular    20ae3f8b5323674fe6e537bc91928841cfc2a00c1b36522fd25370bb6fa89d36
21  Regular    bc704ff2bc676dbf48ee41b9e11481c1387bf758ad318f2428f336e3fecc6660
22  Amateur    200db0417ee70863c7e2a0f214c737476fb86de5869d0b907a077d726357e687
23  Beginner   f9ac013b2f0bc2bd4928a6a0fc8a0aae8b5c4f2670cf9e18f547b7e72034c965
24  Beginner   89c8e07d6a2aa102d9cd05086d51b2e41195c9c807dd976a06f4262ff36d0cca
25  Amateur    119f01b9877fc5ea0073d05602a353b91c4b48e4cf02f42bb8d661b46a34b760
26  Regular    5baba1651a0b92788bc0d6dcdf00be64af1cf9f0015bbeed204ddabd1d872e83
27  Regular    50cec73a632e4be7b155c3df5165de28b2c5baf092abcb7f509f5645776a56c2
28  Veteran    f8acd26a5e452b682b9f8b20108caef1ee2e745efe08e95806980bd2388a3fea
29  Amateur    4b01bce3f141289709e8278b02ba5d2aaa7105d7ccb9c7deb37670a80e332774
30  Veteran    951e54f7376e2b2f0915e9e3646c701af4a2fe839385b13f9e0084b08f8070bd
⋮   ⋮          ⋮
165 Regular    c121e4d197469bea90e21c0495001f4e21824adb98cbc6a40d54e66617cee174
166 Amateur    7096b30972a32029244fc6171f21bc5996b51b8d75df7a94f003dead428988f9
167 Beginner   42eafe96ed5c1684e3b5cc614d1b01a117173d3ec6898abcf1177d9822bd39f7
168 Veteran    9ba67e127e4e70d909f6237644bb4674b17bc6ae5c9e735f88cfc50e22b499c6
169 Veteran    4bfad3613c71ace05644bf210195d9fb0d3d9513753ad2f8a16d1a80699bb906
170 Pro        060aca80f8cfbf1c91553a72f4d5ec8034764b05ab59fe8e1cf0eee9a7b67967
171 Beginner   80afc8e7137de6a232421e926c1e6e64ddeef1d8157c4439746bc00fcf91e8a7
172 Veteran    af6b2350478c6bd6af97c91c7eed1d121b82676d1d519ef5b6cfa16dd451fe27
173 Regular    7b17513f11968feaf6b02977885c436dc2a4549489ca25ef03022f9fbae19d81
174 Veteran    171d3c323c6430ffe0722c931f4cced5c48935f6804e0ff250964e4c41da55b1
175 Amateur    55d24216db39c27e1f17cc43d3127cbf8ed76ada6d098202b53ded319855e2c1
176 Pro        e1e5b1d36ab7680b6927fd3cb619c2b5373167750f90f7a21bf67b5d9b0fd73f
177 Veteran    a1e0438d568b9c05a93cadaf99969e4d44794d19dea31edd723cbc916f878c33
178 Amateur    9955ab948064150d3686ef564389bdc6d6c60bc620a5ce3084b3dec4a7a006a7
179 Veteran    6b1cdc07fcc1f7ea09509341fd245dd34fdba386f14a493e9107c18604baedc9
180 Amateur    93efabc9f7de58f44c457bac715cf8f9f44cd88cc574fc02624cac194d2f0ea5
181 Amateur    42382bb2af563e6979c5b84d288cbb49bb2ef90b1bcf196c2902da4ce20eb7f3
182 Pro        f7875ae87a61632030d5c4029ee8cf081be7047b2b4a9c04ab5a706f59786197
183 Amateur    24d4892c2c3ce11d3e54c3bf31ee218901cac7a2f564911d67424c8fdf0874fe
184 Pro        d46bd29a2ed08e3500bd8729085ef4b6f0ca65baf4c756f88b6bedf7a18e0352
185 Regular    8e98b6db2053af0bc0e62cd55bcea5a08f23986dec3d02ca520ea039517e6744
186 Veteran    ba24bebe588a34ac546f8559850c65bc90cd9d51b821581bd6e25cff437a1081
187 Amateur    e3f0ad9aadd27f3d1d9197e58546d045018daa767675033d9af9a2b74e763739
188 Beginner   8c9d043ebb3689e679a37bfed30ea96272bcd14689ed2d9fcd68a4ae0c1663bc
189 Amateur    514ebbaa30f0d162127e065ab780892b7930cf8d75944d5eb09c91c02d6026c7
190 Amateur    644fe4200c19a73768b3fa598afcbd0948f7557925b7f17166285da23af31cc6
191 Amateur    b6e9e593b9ec51c5e335457341c324c34a2239531e1890b93ca52ac1dc76b08f
192 Veteran    71453e425f07d10da4fa2b349c83e73ccdf0fb3312f778b35c5802c3292c87bd
193 Amateur    d572f391d452b76ea2d7e5e53a3d38bfd7499c7399db299bd4fedb06a46ad5bb
194 Amateur    f19e136ddde68f365afc860c725ccff54307dedd13968e896a9f890c40aea436
    played_hours gender            Age
1   30.3         Male               9
2    3.8         Male              17
3    0.0         Male              17
4    0.7         Female            21
5    0.1         Male              21
6    0.0         Female            17
7    0.0         Female            19
8    0.0         Male              21
9    0.1         Male              47
10   0.0         Female            22
11   1.6         Female            23
12   0.0         Male              17
13   1.5         Female            25
14   0.2         Male              22
15   0.0         Non-binary        17
16   0.0         Male              22
17   0.0         Female            17
18  48.4         Female            17
19   0.5         Male              17
20   0.6         Male              19
21   0.3         Male              58
22   0.1         Female            17
23   1.0         Male              17
24   0.0         Male              17
25   0.7         Female            21
26   0.6         Female            28
27   0.0         Male              17
28   0.0         Male              23
29   1.8         Male              23
30   0.1         Male              18
⋮   ⋮            ⋮                 ⋮
165  0.1         Male              21
166  1.0         Male              26
167  0.3         Female            17
168  0.1         Male              17
169  0.1         Male              17
170  0.4         Male              21
171  1.8         Male              32
172  0.0         Agender           20
173  0.0         Male              50
174  0.0         Male              17
175  0.3         Male              17
176  0.0         Non-binary        17
177  2.7         Non-binary        21
178  0.4         Two-Spirited      17
179  0.1         Non-binary        17
180  2.1         Male              24
181  0.8         Female            22
182  0.2         Male              17
183 32.0         Male              22
184  1.7         Male              17
185  0.1         Male              18
186  0.1         Female            44
187  0.0         Male              17
188  0.0         Female            17
189  0.0         Male              17
190  0.0         Male              20
191  0.0         Female            17
192  0.3         Male              22
193  0.0         Prefer not to say 57
194  2.3         Male              17